# ~/.zshrc -- Oh My Zsh + Starship
export ZSH="$HOME/.oh-my-zsh"

# Starship handles the prompt; use an empty OMZ theme.
ZSH_THEME=""

# Behavior
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_COMPFIX="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(
    git
    docker
    docker-compose
    pip
    python
    npm
    sudo
    colored-man-pages
    extract
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-completions
    zsh-history-substring-search
)

# Add zsh-completions to fpath before compinit (run by OMZ source)
fpath+=(${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src)

source $ZSH/oh-my-zsh.sh

# ---------- History ----------
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=200000
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt EXTENDED_HISTORY

# ---------- Options ----------
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt CORRECT
setopt INTERACTIVE_COMMENTS

# ---------- Environment ----------
export SHELL=/usr/bin/zsh
export EDITOR=vim
export PAGER=less
export LESS='-R -i -M -w -z-4'
export CLICOLOR=1

# ---------- Aliases ----------
alias ll='ls -alhF --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias grep='grep --color=auto'
alias gs='git status -sb'
alias gd='git diff'
alias gdc='git diff --cached'
alias gco='git checkout'
alias gcm='git commit -m'
alias gp='git push'
alias gl='git pull'
alias glog='git log --oneline --graph --decorate --all'
alias gb='git branch'
alias ga='git add'
alias dc='docker compose'

# ---------- fzf ----------
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f /usr/share/doc/fzf/examples/completion.zsh ] && source /usr/share/doc/fzf/examples/completion.zsh

# ---------- History substring search (up/down arrow) ----------
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# ---------- Prompt ----------
command -v starship >/dev/null 2>&1 && eval "$(starship init zsh)"

# ---------- Local overrides ----------
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
